"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { ExternalLink, FileText, Plus, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogTrigger } from "@/components/ui/dialog";
import { Select } from "@/components/ui/select";
import { Field, inputClass } from "@/components/shared/form-field";
import { IconTooltip } from "@/components/ui/tooltip";

type ClientFile = {
  id: string;
  name: string;
  category: string;
  source: string;
  url: string;
  createdAt: string;
};

const CATEGORY_OPTIONS = [
  { value: "SOP", label: "SOP" },
  { value: "PROPERTIES", label: "Properties" },
  { value: "INVOICES", label: "Invoices" },
  { value: "KNOWLEDGE", label: "Knowledge" },
  { value: "OTHER", label: "Other" },
];

const SOURCE_OPTIONS = [
  { value: "GOOGLE_DRIVE", label: "Google Drive" },
  { value: "URL", label: "External URL" },
  { value: "GENERATED", label: "Generated by Charlie HQ" },
  { value: "EXTERNAL", label: "Other external source" },
];

async function submitJson(url: string, method: string, payload?: Record<string, any>) {
  const res = await fetch(url, {
    method,
    headers: payload ? { "Content-Type": "application/json" } : undefined,
    body: payload ? JSON.stringify(payload) : undefined,
  });
  const data = await res.json().catch(() => ({}));
  if (!res.ok) throw new Error(data.error ?? "Request failed");
  return data;
}

function AddFileModal({ clientId }: { clientId: string }) {
  const router = useRouter();
  const [open, setOpen] = useState(false);
  const [category, setCategory] = useState("OTHER");
  const [source, setSource] = useState("URL");
  const [submitting, setSubmitting] = useState(false);

  async function handleSubmit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setSubmitting(true);
    const form = new FormData(event.currentTarget);
    try {
      await submitJson("/api/client-files", "POST", {
        clientId,
        name: String(form.get("name") ?? "").trim(),
        category,
        source,
        url: String(form.get("url") ?? "").trim(),
      });
      toast.success("File added");
      setOpen(false);
      router.refresh();
    } catch (err: any) {
      toast.error(err.message);
      setSubmitting(false);
    }
  }

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <Button variant="outline" className="h-8 px-3 text-xs">
          <Plus className="h-3.5 w-3.5" /> Add File
        </Button>
      </DialogTrigger>
      <DialogContent title="Add Client File" className="max-w-md">
        <form onSubmit={handleSubmit} className="space-y-3">
          <p className="text-xs text-muted-foreground">
            Charlie HQ links to files rather than storing raw uploads today — paste a link to the document (Google
            Drive, an external URL, or a generated doc).
          </p>
          <Field label="Name">
            <input name="name" required className={inputClass} placeholder="e.g. Cleaning SOP" />
          </Field>
          <Field label="Category">
            <Select value={category} onValueChange={setCategory} options={CATEGORY_OPTIONS} />
          </Field>
          <Field label="Source">
            <Select value={source} onValueChange={setSource} options={SOURCE_OPTIONS} />
          </Field>
          <Field label="Link">
            <input name="url" required type="url" className={inputClass} placeholder="https://..." />
          </Field>
          <Button type="submit" disabled={submitting} className="w-full">
            {submitting ? "Saving..." : "Add File"}
          </Button>
        </form>
      </DialogContent>
    </Dialog>
  );
}

function DeleteFileButton({ id }: { id: string }) {
  const router = useRouter();
  const [busy, setBusy] = useState(false);
  return (
    <IconTooltip label="Delete file">
      <button
        disabled={busy}
        onClick={async () => {
          if (!confirm("Remove this file link?")) return;
          setBusy(true);
          try {
            await submitJson(`/api/client-files/${id}`, "DELETE");
            router.refresh();
          } catch (err: any) {
            toast.error(err.message);
            setBusy(false);
          }
        }}
        className="rounded-lg p-1.5 text-muted-foreground hover:bg-danger/10 hover:text-danger"
        aria-label="Delete file"
      >
        <Trash2 className="h-4 w-4" />
      </button>
    </IconTooltip>
  );
}

export function ClientFilesPanel({ clientId, files, canManage }: { clientId: string; files: ClientFile[]; canManage: boolean }) {
  return (
    <Card>
      <CardHeader className="flex flex-row items-center justify-between gap-3">
        <CardTitle>Files</CardTitle>
        {canManage && <AddFileModal clientId={clientId} />}
      </CardHeader>
      <CardContent className="p-0">
        {files.length === 0 ? (
          <div className="p-6 text-center">
            <FileText className="mx-auto h-6 w-6 text-muted-foreground" />
            <p className="mt-2 text-sm text-muted-foreground">No files linked yet.</p>
          </div>
        ) : (
          files.map((file) => (
            <div key={file.id} className="flex items-center justify-between gap-3 border-t border-border/60 px-5 py-3 text-sm first:border-0">
              <div className="min-w-0">
                <a href={file.url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1.5 font-medium hover:text-primary hover:underline">
                  {file.name} <ExternalLink className="h-3 w-3 shrink-0" />
                </a>
                <p className="text-xs text-muted-foreground">
                  {file.category.charAt(0) + file.category.slice(1).toLowerCase()} · {file.source.replace(/_/g, " ").toLowerCase()}
                </p>
              </div>
              {canManage && <DeleteFileButton id={file.id} />}
            </div>
          ))
        )}
      </CardContent>
    </Card>
  );
}
